// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsRDBsJuYzNq05qhwcKKhXmJWUv9d4C8',
    appId: '1:864586003077:web:29379eee344ac6045d2fec',
    messagingSenderId: '864586003077',
    projectId: 'e-commerce-mobile-applic-883c0',
    authDomain: 'e-commerce-mobile-applic-883c0.firebaseapp.com',
    storageBucket: 'e-commerce-mobile-applic-883c0.appspot.com',
    measurementId: 'G-5W6K6V3PEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-xjeobNQ7c67ba-P8mNXfUOtFL2OaCU',
    appId: '1:864586003077:android:bdacc2ea2e3f6e1b5d2fec',
    messagingSenderId: '864586003077',
    projectId: 'e-commerce-mobile-applic-883c0',
    storageBucket: 'e-commerce-mobile-applic-883c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCw1_MVXj8Oj6LsYguOfRQ-lGc6KInh4',
    appId: '1:864586003077:ios:42981ce7da359f0e5d2fec',
    messagingSenderId: '864586003077',
    projectId: 'e-commerce-mobile-applic-883c0',
    storageBucket: 'e-commerce-mobile-applic-883c0.appspot.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCw1_MVXj8Oj6LsYguOfRQ-lGc6KInh4',
    appId: '1:864586003077:ios:42981ce7da359f0e5d2fec',
    messagingSenderId: '864586003077',
    projectId: 'e-commerce-mobile-applic-883c0',
    storageBucket: 'e-commerce-mobile-applic-883c0.appspot.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdsRDBsJuYzNq05qhwcKKhXmJWUv9d4C8',
    appId: '1:864586003077:web:ba166dd8552ddba35d2fec',
    messagingSenderId: '864586003077',
    projectId: 'e-commerce-mobile-applic-883c0',
    authDomain: 'e-commerce-mobile-applic-883c0.firebaseapp.com',
    storageBucket: 'e-commerce-mobile-applic-883c0.appspot.com',
    measurementId: 'G-E22BF1XV1Z',
  );

}